### ISSUE TITLE
medium-sdk seems absent from modules

### ISSUE THREAD

**Issue by AyymericArn** [InfraWay/post-medium-action#4] opened 2021-11-29 21:09 UTC
Hello, thanks for this useful action. When using it, I faced the following error :

```Error: Cannot find module '@redcode/medium-sdk'
Require stack:
- /home/runner/work/_actions/infraway/post-medium-action/v1.5.0/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/infraway/post-medium-action/v1.5.0/index.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/infraway/post-medium-action/v1.5.0/index.js'
  ]
}
```

Maybe I misconcieve something about GH actions but I was thinking I had no installation to proceed in my own .yml file. Is the module lacking in the modules of the action template ? I saw it was not maintained anymore, do you think it is related to my issue ?

**Comment by higgins** [comment] 2021-12-19 02:07
Hey @maZahaca, I finally got around to integrating this (thanks again for your patch on https://github.com/InfraWay/post-medium-action/issues/3)

I'm getting the same error as @AyymericArn ; any ideas? Maybe `@redcode/medium-sdk` wasn't bundled with the shipped package?

```
Run InfraWay/post-medium-action@v1.5.0
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@redcode/medium-sdk'
Require stack:
- /home/runner/work/_actions/InfraWay/post-medium-action/v1.5.0/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/InfraWay/post-medium-action/v1.5.0/index.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/InfraWay/post-medium-action/v1.5.0/index.js'
  ]
}
```

**Comment by AseiSugiyama** [comment] 2021-12-23 12:28
I faced the same issue. This Action seems to be useful and it would be great if I can use this action in my CI/CD.

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@redcode/medium-sdk'
Require stack:
- /home/runner/work/_actions/InfraWay/post-medium-action/v1.5.0/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/InfraWay/post-medium-action/v1.5.0/index.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/InfraWay/post-medium-action/v1.5.0/index.js'
  ]
}
```

**Comment by ksingh7** [comment] 2022-02-07 18:14
@maZahaca 


![image](https://user-images.githubusercontent.com/9701902/152847285-f4df0ed2-6faa-42a0-b6e3-a43dba62c2c6.png)

**Comment by Nevvulo** [comment] 2022-02-08 12:45
Also experiencing the same issue. Tried to manually install `@redcode/medium-sdk` but didn't have much luck - this is blocking me from using the action at all

**Comment by eugeneromero** [comment] 2022-02-08 12:49
It seems there isn't much activity on this Action these days... until this breaking bug is fixed, I can recommend the [other Github Action for Medium](https://github.com/marketplace/actions/post-to-medium-action), been using that one for a bit now and it has worked well for me.

**Comment by maZahaca** [comment] 2022-02-08 13:14
Thanks for reporting, I will have a look shortly ✋

**Comment by maZahaca** [comment] 2022-02-08 13:15
All submodules should be just be placed withing an action, let me check it

**Comment by maZahaca** [comment] 2022-02-08 13:28
Apologize for the issue 🙏 
I've missed this module to be pushed.
Now it's fixed and tested in [v1.6.0](https://github.com/InfraWay/post-medium-action/releases/tag/v1.6.0)

**Comment by maZahaca** [comment] 2022-02-08 16:08
@AyymericArn I appreciate if you could review this

**Comment by maZahaca** [comment] 2022-02-10 11:13
Closing for now, feel free to reopen if reproduced

**Closed as completed by maZahaca** 2022-02-10 11:13 UTC
